version: 1.0.0.{build}
environment:
  NugetPushKey:
    secure: Fr6Et35ii82/P5ZjfsKoIomda8gim+SKJkklwChGm5Jm2+wd/5uyQYbwAP4M7UTv
cache: packages

install:
  - git submodule update --init --recursive
build_script:
  - powershell Build\Build.ps1 -Configuration Release -Version %APPVEYOR_BUILD_VERSION% -NugetPushKey %NugetPushKey%

test: off
deploy: off
